Repository KlimaDAO/klimadao, pull requests merged in 2023-11, with the labels that each got.

#1812 carbon: enable card titles to wrap on mobile
  carbon/components/cards/ChartCard/index.tsx
  carbon/components/cards/ChartCard/styles.module.scss
Labels: QA done

#1805 Prevent charts from redrawing when scrolling on mobile
  carbon/components/charts/helpers/ChartWrapper/index.tsx
Labels: QA done

#1817 make tables scrollable on mobile
  carbon/components/charts/helpers/DataTable/DataTableClientWrapper/index.tsx
  carbon/components/charts/helpers/DataTable/DataTableClientWrapper/styles.module.scss
  carbon/components/charts/helpers/DataTable/configurations/styles.module.scss
Labels: carbonmark-data

#1816 Makka / #1815 change text & link to external form
  carbonmark/components/pages/Home/index.tsx
  carbonmark/locale/en-pseudo/messages.po
  carbonmark/locale/en/messages.po
  lib/constants/index.ts
Labels: QA done

#1830 fix desktop colors for header buttons
  carbon/components/Layout/styles.module.scss
Labels: carbonmark-data

#1833 carbon: make the whole fact clickable
  carbon/components/cards/overview/TokensPriceCard/index.tsx
  carbon/components/cards/overview/TokensPriceCard/styles.module.scss
  carbon/components/charts/helpers/CoinTiles/index.tsx
  carbon/components/charts/helpers/CoinTiles/styles.module.scss
Labels: carbonmark-data

#1839 center chart legend on mobile
  carbon/components/charts/helpers/KAreaChart/index.tsx
  carbon/components/charts/helpers/KBarChart/index.tsx
  carbon/components/charts/helpers/KLineChart/index.tsx
  carbon/components/charts/helpers/styles.module.scss
Labels: carbonmark-data

#1849 carbon: migrate brand colors to klima green
  carbon/app/[locale]/globals.css
  carbon/app/favicon.ico
  carbon/components/Graphics/CarbonmarkDataLogo.tsx
  carbon/components/Layout/DesktopSidebar/styles.module.scss
  carbon/components/Layout/MobileBottomNav/styles.module.scss
  carbon/components/Layout/MobileMenuButton/styles.module.scss
  carbon/components/PageHeader/styles.module.scss
Labels: carbonmark-data

#1864 Makka / 1862 revert icon imports in lib
  lib/components/CopyValueButton/index.tsx
Labels: HIGH PRIORITY

#1879 Makka / address issue with wallet connect loading
  lib/components/Web3Context/index.tsx
  lib/utils/useProvider/index.tsx
Labels: HIGH PRIORITY

#1883 carbon: rightsize retirement trends page
  carbon/components/pages/retirementTrends/TwoColumnRetirementTrendsTab/index.tsx
  carbon/theme/layout.module.scss
Labels: carbonmark-data

#1859 Makka / 1791 prevent users from retiring listed tonnes
  carbonmark/components/pages/Portfolio/AssetProject/index.tsx
  carbonmark/components/pages/Portfolio/AssetProject/styles.ts
  carbonmark/components/pages/Portfolio/Retire/RetireForm/index.tsx
  carbonmark/components/pages/Portfolio/Retire/index.tsx
  carbonmark/lib/actions.ts
  carbonmark/lib/formatNumbers.ts
  carbonmark/lib/types/carbonmark.types.ts
  carbonmark/locale/en-pseudo/messages.po
  carbonmark/locale/en/messages.po
Labels: HIGH PRIORITY

#1900 carbon: add explore button to mobile menu
  carbon/components/ExploreMarketplaceButton/index.tsx
  carbon/components/ExploreMarketplaceButton/styles.module.scss
  carbon/components/Layout/MobileMenuButton/index.tsx
  carbon/components/Layout/MobileMenuButton/styles.module.scss
  carbon/components/PageHeader/PageHeader.tsx
  carbon/components/PageHeader/styles.module.scss
Labels: carbonmark-data

#1899 carbon: add carbonmark and klimadao footer links
  carbon/components/Layout/Footer/index.tsx
Labels: carbonmark-data

#1705 Makka / 1690 remove scrollbar width
  carbonmark/components/pages/Portfolio/Retire/CustomizableModal/styles.ts
  carbonmark/components/shared/Modal/styles.ts
Labels: QA done

#1909 [navigation] fix hamburger animation
  carbonmark/components/shared/Header/styles.ts
  carbonmark/components/shared/Navigation/ToggleNavButton.tsx
  carbonmark/components/shared/Navigation/styles.ts
  carbonmark/package.json
  package-lock.json
Labels: QA done

#1933 Emc/fix-request-params-on-kubb-hooks
  carbonmark/.generated/carbonmark-api-sdk/client.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/operations.ts
  carbonmark/.generated/carbonmark-api.schema.json
  carbonmark/components/UserTracker/index.tsx
  carbonmark/components/pages/Portfolio/Retire/index.tsx
  carbonmark/components/pages/Portfolio/index.tsx
  carbonmark/components/pages/Projects/ProjectsController/index.tsx
  carbonmark/components/pages/Projects/index.tsx
  carbonmark/components/pages/Retire/FromPortfolio/index.tsx
  carbonmark/components/pages/Retirements/SingleRetirement/BeneficiaryDetails/index.tsx
  carbonmark/components/pages/Users/SellerConnected/index.tsx
  carbonmark/components/pages/Users/SellerUnconnected/index.tsx
  carbonmark/hocs/ConditionalErrorBoundary/NotFoundError.ts
  carbonmark/hocs/ConditionalErrorBoundary/index.tsx
  carbonmark/hooks/useFetchProjects.ts
  carbonmark/lib/api/client.ts
  carbonmark/lib/getProjectsQueryString.ts
  carbonmark/pages/portfolio/index.tsx
  carbonmark/pages/users/[user].tsx
Labels: QA needed

#1910 Move icons to the lib module
  app/components/CarbonBalancesCard/index.tsx
  app/components/views/ChooseBond/index.tsx
  app/lib/getTokenInfo.ts
  carbon/lib/protocols.tsx
  carbon/lib/tokens.tsx
  lib/package.json
  lib/resources/declaration.d.ts
  lib/resources/icons/BCT-KLIMA-LP.png
  lib/resources/icons/BCT.png
  lib/resources/icons/C3T.png
  lib/resources/icons/Fiat.png
  lib/resources/icons/KLIMA-MCO2-LP.png
  lib/resources/icons/KLIMA-USDC-LP.png
  lib/resources/icons/KLIMA.png
  lib/resources/icons/MCO2.png
  lib/resources/icons/NBO.png
  lib/resources/icons/NCT.png
  lib/resources/icons/TCO2.png
  lib/resources/icons/UBO.png
  lib/resources/icons/USDC.png
  lib/resources/icons/index.ts
  lib/resources/index.ts
  package-lock.json
Labels: QA needed

#1941 fix #1927 only fetch project if id is present
  carbonmark/pages/retirements/[beneficiary]/[retirement_index].tsx
Labels: QA done

#1942 fix:1940 Use corrrect address for fetch check
  carbonmark/components/pages/Users/SellerConnected/Forms/EditProfile.tsx
  carbonmark/components/pages/Users/SellerConnected/index.tsx
  carbonmark/components/pages/Users/SellerUnconnected/index.tsx
Labels: QA needed
