Repository KlimaDAO/klimadao, pull requests merged in 2023-09, with the labels that each got.

#1505 cleanup carbonmark-data css
  carbonmark-data/app/[locale]/globals.css
  carbonmark-data/components/ChangeLanguageButton/styles.module.scss
  carbonmark-data/components/Layout/style.module.scss
  carbonmark-data/components/OptionsSwitcher/styles.module.scss
  carbonmark-data/components/Skeleton/styles.module.scss
  carbonmark-data/components/cards/ChartCard/styles.module.scss
  carbonmark-data/components/charts/DailyCreditsChart/Chart.tsx
  carbonmark-data/components/charts/HistoricalPriceChart/Chart.tsx
  carbonmark-data/components/charts/helpers/styles.module.scss
  carbonmark-data/components/pages/DetailPage/styles.module.scss
  carbonmark-data/theme/layout.module.scss
Labels: carbonmark-data

#1407 Unify modal styling
  carbonmark/components/Transaction/index.tsx
  carbonmark/components/pages/Portfolio/Retire/RetireModal/index.tsx
  carbonmark/components/pages/Project/Purchase/Listing/PurchaseModal.tsx
  carbonmark/components/pages/Project/Purchase/Pool/PurchaseModal.tsx
  carbonmark/components/pages/Project/Retire/Pool/RetireModal.tsx
Labels: QA done

#1519 fix: resource sort by tippy dropdown styling
  carbonmark/components/pages/Resources/SortyByDropDown/index.tsx
  carbonmark/components/pages/Resources/SortyByDropDown/styles.ts
Labels: QA done

#1551 handles MinPurchaseRequired Error
  carbonmark/components/pages/Project/Retire/Pool/CreditCardModal.tsx
  carbonmark/components/pages/Project/Retire/Pool/RetireForm.tsx
  carbonmark/components/pages/Project/Retire/Pool/RetireInputs.tsx
  carbonmark/components/pages/Project/Retire/Pool/TotalValues.tsx
  carbonmark/lib/fiat/fiatInfo.ts
  carbonmark/locale/en-pseudo/messages.po
  carbonmark/locale/en/messages.po
Labels: QA done

#1577 Makka / #1434 format qty value with decimals
  carbonmark/components/pages/Retire/Activity/Table.tsx
Labels: QA needed

#1587 #1490 Refactor(/projects/:id) only fetch unexpired listings
  carbonmark-api/src/.generated/types/marketplace.types.ts
  carbonmark-api/src/.generated/types/marketplaceMumbai.types.ts
  carbonmark-api/src/graphql/marketplace.gql
  carbonmark-api/src/graphql/marketplaceMumbai.gql
  carbonmark-api/src/utils/helpers/fetchMarketplaceListings.ts
Labels: carbonmark-api

#1589 #1491 feat(/users/:id): support expiresAfter querystring
  carbonmark-api/src/.generated/types/marketplace.types.ts
  carbonmark-api/src/.generated/types/marketplaceMumbai.types.ts
  carbonmark-api/src/graphql/marketplace.gql
  carbonmark-api/src/graphql/marketplaceMumbai.gql
  carbonmark-api/src/routes/users/get.schema.ts
  carbonmark-api/src/routes/users/get.ts
  carbonmark-api/src/routes/users/get.utils.ts
Labels: carbonmark-api

#1588 #1489 refactor(/projects): only fetch unexpired listings
  carbonmark-api/src/.generated/types/marketplace.types.ts
  carbonmark-api/src/.generated/types/marketplaceMumbai.types.ts
  carbonmark-api/src/graphql/marketplace.gql
  carbonmark-api/src/graphql/marketplaceMumbai.gql
  carbonmark-api/src/routes/projects/[id]/get.schema.ts
  carbonmark-api/src/routes/projects/[id]/get.ts
  carbonmark-api/src/routes/projects/get.schema.ts
  carbonmark-api/src/routes/projects/get.ts
  carbonmark-api/src/routes/projects/get.utils.ts
  carbonmark-api/src/routes/users/get.schema.ts
  carbonmark-api/src/utils/helpers/fetchMarketplaceListings.ts
Labels: carbonmark-api

#1576 Makka / #1424 add cc transitions
  carbonmark/components/pages/Project/Retire/Pool/RetireForm.tsx
  carbonmark/components/pages/Project/Retire/Pool/TotalValues.tsx
  carbonmark/components/pages/Project/Retire/Pool/styles.ts
Labels: QA done
