Repository KlimaDAO/klimadao, pull requests merged in 2023-12, with the labels that each got.

#1537 Tufnel/integrate digital carbon graph into get.ts
  carbonmark-api/src/.generated/types/digitalCarbon.types.ts
  carbonmark-api/src/graphql/digitalCarbon.fragments.gql
  carbonmark-api/src/graphql/digitalCarbon.gql
  carbonmark-api/src/models/Project.model.ts
  carbonmark-api/src/routes/projects/get.ts
  carbonmark-api/src/routes/projects/get.utils.ts
  carbonmark-api/src/utils/helpers/utils.ts
  carbonmark-api/test/fixtures/digitalCarbon.ts
  carbonmark-api/test/plugins/rate-limit.test.ts
  carbonmark-api/test/routes/categories/get.test.ts
  carbonmark-api/test/routes/countries/get.test.ts
  carbonmark-api/test/routes/projects/[id]/get.test.ts
  carbonmark-api/test/routes/projects/get.test.ts
  carbonmark-api/test/routes/vintages/get.test.ts
Labels: QA needed

#1945 Emc/fix/1944-profile-portfolio-issues
  carbonmark-api/src/models/User.model.ts
  carbonmark/components/pages/Portfolio/PortfolioSidebar.tsx
  carbonmark/components/pages/Portfolio/Retire/index.tsx
  carbonmark/components/pages/Portfolio/index.tsx
  carbonmark/components/pages/Retire/FromPortfolio/index.tsx
  carbonmark/components/pages/Users/ProfileHeader/index.tsx
  carbonmark/components/pages/Users/ProfileSidebar/index.tsx
  carbonmark/components/pages/Users/SellerConnected/index.tsx
  carbonmark/components/pages/Users/SellerUnconnected/index.tsx
  carbonmark/components/pages/Users/index.tsx
  carbonmark/pages/portfolio/index.tsx
  carbonmark/pages/users/[user].tsx
  site/components/pages/Retirements/SingleRetirement/index.tsx
Labels: QA done

#1966 Fix projects default pool detection
  carbonmark-api/src/utils/helpers/fetchProjectPoolInfo.ts
Labels: QA done

#1949 Retirement page fallback improvements
  carbonmark/components/pages/Retirements/SingleRetirement/ProjectDetails/index.tsx
  carbonmark/components/pages/Retirements/SingleRetirement/index.tsx
  carbonmark/components/pages/Retirements/SingleRetirement/styles.ts
  carbonmark/pages/retirements/[beneficiary]/[retirement_index].tsx
  examples/nextjs-typescript-integration/utils/fetchGasPrices.ts
  lib/constants/index.ts
  lib/types/subgraph.ts
  site/pages/retirements/[beneficiary]/[retirement_index].tsx
Labels: HIGH PRIORITY, QA needed

#1990 fix: Resolve v2.0.0 and v2.0.3 api differences
  carbonmark-api/src/routes/projects/get.ts
  carbonmark-api/src/routes/projects/get.utils.ts
  carbonmark/components/pages/Project/index.tsx
  carbonmark/lib/types/carbonmark.guard.ts
  package-lock.json
Labels: QA needed

#2013 fix:1987 trim Category strings in [id]/get and projects/get
  carbonmark-api/package.json
  carbonmark-api/src/routes/projects/[id]/get.ts
  carbonmark-api/src/routes/projects/get.utils.ts
Labels: QA done

#1674 /users/login to /login
  carbonmark-api/package.json
  carbonmark-api/src/routes/categories/get.ts
  carbonmark-api/src/routes/login/post.schema.ts
  carbonmark-api/src/routes/login/post.ts
  carbonmark-api/src/routes/login/verify/post.schema.ts
  carbonmark-api/src/routes/login/verify/post.ts
  carbonmark-api/src/routes/users/[walletOrHandle]/get.schema.ts
  carbonmark-api/src/routes/users/[walletOrHandle]/get.ts
  carbonmark-api/src/routes/users/[walletOrHandle]/get.utils.ts
  carbonmark-api/src/routes/users/[wallet]/put.schema.ts
  carbonmark-api/src/routes/users/[wallet]/put.ts
  carbonmark-api/test/flows/authentication.test.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/postLogin.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/postLoginVerify.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/usePostLogin.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/usePostLoginVerify.ts
  carbonmark/.generated/carbonmark-api-sdk/types/PostLogin.ts
  carbonmark/.generated/carbonmark-api-sdk/types/PostLoginVerify.ts
  package-lock.json
Labels: QA needed

#2022 Display price of the default pool on default pools' projects
  carbonmark/components/ProjectCard/index.tsx
  carbonmark/components/pages/Retire/index.tsx
Labels: QA done

#2025 Use carbonmark api version 4.x.x
  carbonmark/.generated/carbonmark-api-sdk/clients/index.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/operations.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/postUsersLogin.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/postUsersLoginVerify.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/index.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/usePostUsersLogin.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/usePostUsersLoginVerify.ts
  carbonmark/.generated/carbonmark-api-sdk/schemas/DetailedProject.json
  carbonmark/.generated/carbonmark-api-sdk/schemas/Listing.json
  carbonmark/.generated/carbonmark-api-sdk/schemas/Project.json
  carbonmark/.generated/carbonmark-api-sdk/schemas/User.json
  carbonmark/.generated/carbonmark-api-sdk/types/DetailedProject.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetProjects.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetProjectsId.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetUsersWalletorhandle.ts
  carbonmark/.generated/carbonmark-api-sdk/types/Listing.ts
  carbonmark/.generated/carbonmark-api-sdk/types/PostUsersLogin.ts
  carbonmark/.generated/carbonmark-api-sdk/types/PostUsersLoginVerify.ts
  carbonmark/.generated/carbonmark-api-sdk/types/Project.ts
  carbonmark/.generated/carbonmark-api-sdk/types/User.ts
  carbonmark/.generated/carbonmark-api-sdk/types/index.ts
  carbonmark/.generated/carbonmark-api.schema.json
  carbonmark/components/pages/Portfolio/CarbonmarkAssets.tsx
  carbonmark/components/pages/Portfolio/PortfolioSidebar.tsx
  carbonmark/components/pages/Portfolio/index.tsx
  carbonmark/components/pages/Project/BuyOptions/SellerListing.tsx
  carbonmark/components/pages/Retire/FromPortfolio/index.tsx
  carbonmark/components/pages/Users/ProfileSidebar/index.tsx
  carbonmark/components/pages/Users/SellerConnected/index.tsx
  carbonmark/lib/api.ts
  carbonmark/lib/constants.ts
  carbonmark/lib/listingsGetter.ts
Labels: QA done

#2029 fix:1958 Add filters to graph request on marketplace
  carbonmark-api/package.json
  carbonmark-api/src/.generated/types/marketplace.types.ts
  carbonmark-api/src/graphql/marketplace.gql
  carbonmark-api/src/routes/projects/get.ts
Labels: QA done

#2040 Add link to legacy app for carbon offsets
  app/components/views/Offset/index.tsx
  carbonmark-api/postman_collection.json
  lib/constants/index.ts
Labels: QA done

#2041 Fix assets details token identification for the pool purchase page.
  carbonmark/components/AssetDetails/index.tsx
  carbonmark/components/AssetDetails/styles.ts
  carbonmark/components/pages/Project/Purchase/Pool/PurchaseForm.tsx
  carbonmark/components/pages/Project/Purchase/styles.ts
  carbonmark/components/pages/Project/Retire/Pool/AssetDetails.tsx
  carbonmark/components/pages/Project/Retire/Pool/RetireForm.tsx
  carbonmark/components/pages/Project/Retire/Pool/styles.ts
Labels: QA done

#2023 [FE] Makka / #1992 pay with bank transfer FE changes
  app/locale/en-pseudo/messages.po
  app/locale/en/messages.po
  carbon/locale/en-pseudo/messages.po
  carbon/locale/en/messages.po
  carbonmark/components/pages/Project/PayWithBank/index.tsx
  carbonmark/components/pages/Project/PayWithBank/styles.ts
  carbonmark/components/pages/Project/Purchase/Pool/PurchaseForm.tsx
  carbonmark/components/pages/Project/Retire/Pool/BankTransferModal.tsx
  carbonmark/components/pages/Project/Retire/Pool/RetireForm.tsx
  carbonmark/components/pages/Project/Retire/Pool/RetireInputs.tsx
  carbonmark/components/pages/Project/Retire/Pool/SubmitButton.tsx
  carbonmark/components/pages/Project/Retire/Pool/TotalValues.tsx
  carbonmark/components/pages/Project/Retire/Pool/styles.ts
  carbonmark/components/shared/Form/TextareaField/index.tsx
  carbonmark/components/shared/Form/TextareaField/styles.ts
  carbonmark/lib/actions.redeem.ts
  carbonmark/lib/actions.retire.ts
  carbonmark/lib/constants.ts
  carbonmark/lib/getPaymentMethods.ts
  carbonmark/lib/types/carbonmark.types.ts
  carbonmark/locale/en-pseudo/messages.po
  carbonmark/locale/en/messages.po
  carbonmark/pages/api/bank-transfer/index.ts
  carbonmark/pages/retire/pay-with-bank/index.tsx
  carbonmark/public/icons/Bank.png
  carbonmark/public/icons/Fiat.png
  site/locale/en-pseudo/messages.po
  site/locale/en/messages.po
Labels: QA done
