Repository KlimaDAO/klimadao, pull requests merged in 2023-01, with the labels that each got.

#823 check for infura id and use that provider
  app/.env.example
  app/actions/user.ts
  app/lib/constants.ts
  app/locale/en-pseudo/messages.po
  lib/utils/ens/index.ts
  lib/utils/getInfuraUrl/index.ts
  lib/utils/index.ts
  site/.env.example
  site/components/pages/Pledge/PledgeDashboard/Profile/index.tsx
  site/lib/constants.ts
  site/lib/getAddressByDomain.ts
  site/lib/getBlockRate.ts
  site/lib/getDomainByAddress.ts
  site/lib/getInfuraUrl.ts
  site/lib/secrets.ts
  site/locale/en-pseudo/messages.po
  site/locale/en/messages.po
  site/pages/api/event-demo/index.ts
  site/pages/api/klima-supply/index.ts
  site/pages/event-demo/index.tsx
  site/pages/index.tsx
  site/pages/retirements/[beneficiary]/[retirement_index].tsx
  site/pages/retirements/[beneficiary]/index.tsx
Labels: QA needed

#834 816 retirement pledge ctas
  README.md
  lib/components/Buttons/mixins.ts
  lib/components/Buttons/styles.ts
  site/.env.example
  site/components/pages/Pledge/lib/index.tsx
  site/components/pages/Pledge/lib/pledgeFormAdapter.ts
  site/components/pages/Retirements/SingleRetirement/DownloadCertificateButton/index.tsx
  site/components/pages/Retirements/SingleRetirement/RetirementHeader/index.tsx
  site/components/pages/Retirements/SingleRetirement/RetirementHeader/styles.ts
  site/components/pages/Retirements/SingleRetirement/RetirementMessage/index.tsx
  site/components/pages/Retirements/SingleRetirement/ViewPledgeButton/index.tsx
  site/components/pages/Retirements/SingleRetirement/index.tsx
  site/components/pages/Retirements/SingleRetirement/styles.ts
  site/locale/en-pseudo/messages.po
  site/locale/en/messages.po
  site/pages/pledge/[address].tsx
  site/pages/retirements/[beneficiary]/[retirement_index].tsx
Labels: QA needed

#860 [resources] Resource centre ui enhancements
  site/components/Form/InputField/index.tsx
  site/components/Form/InputField/styles.ts
  site/components/pages/Pledge/PledgeForm/index.tsx
  site/components/pages/Resources/FeaturedArticles/Article.tsx
  site/components/pages/Resources/FeaturedArticles/ArticlesSlider.tsx
  site/components/pages/Resources/FeaturedArticles/styles.ts
  site/components/pages/Resources/ResourcesList/index.tsx
  site/components/pages/Resources/ResourcesList/styles.ts
  site/components/pages/Resources/SortyByDropDown/index.tsx
  site/components/pages/Resources/SortyByDropDown/styles.ts
  site/components/pages/Resources/styles.ts
  site/locale/en/messages.po
Labels: enhancement

#895 hotfix: fix getAllowance
  app/components/views/Offset/index.tsx
Labels: HIGH PRIORITY

#893 Use JsonRpcBatchProvider by default
  app/actions/bonds.ts
  app/actions/offset.ts
  app/actions/user.ts
  app/components/views/Bond/index.tsx
  app/components/views/Home/index.tsx
  app/components/views/Offset/index.tsx
  lib/utils/getRetirement/index.ts
  lib/utils/getStaticProvider/index.ts
  lib/utils/getTreasuryBalance/index.ts
  site/lib/getBalances.ts
Labels: HIGH PRIORITY
