Repository KlimaDAO/klimadao, pull requests merged in 2024-01, with the labels that each got.

#2042 Emc/fix/purchase-endpoints
  carbonmark-api/package.json
  carbonmark-api/postman_collection.json
  carbonmark-api/src/.generated/types/marketplace.types.ts
  carbonmark-api/src/graphql/marketplace.fragments.gql
  carbonmark-api/src/graphql/marketplace.gql
  carbonmark-api/src/routes/projects/[id]/get.ts
  carbonmark-api/src/routes/purchases/[id]/get.schema.ts
  carbonmark-api/src/routes/purchases/[id]/get.ts
  carbonmark-api/src/routes/purchases/[id]/get.utils.ts
  carbonmark-api/src/routes/purchases/get.schema.ts
  carbonmark-api/src/routes/purchases/get.ts
  carbonmark-api/src/routes/purchases/get.utils.ts
  carbonmark-api/src/utils/helpers/cms.utils.ts
  carbonmark-api/test/routes/purchases/[id]/get.test.ts
  carbonmark-api/test/routes/purchases/get.test.ts
  carbonmark-api/test/routes/users/get.test.ts
Labels: QA done

#2060 Hide USDC icon for carbon approvals
  carbonmark/components/Transaction/Approve.tsx
Labels: QA done

#2067 fix back to project button
  carbonmark/components/pages/Project/Purchase/index.tsx
  carbonmark/components/pages/Project/Purchase/styles.ts
  carbonmark/components/pages/Project/Retire/index.tsx
  carbonmark/components/pages/Project/Retire/styles.ts
Labels: QA done

#2066 fix activity designs
  carbonmark/components/Activities/Activity.tsx
  carbonmark/components/Activities/styles.ts
Labels: QA done

#2049 Refactor /projects and /projects/:id routes and change /user/:walletorHandle routes
  carbonmark/.generated/carbonmark-api-sdk/clients/getPurchases.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/index.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/operations.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/index.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/useGetPurchases.ts
  carbonmark/.generated/carbonmark-api-sdk/schemas/DetailedProject.json
  carbonmark/.generated/carbonmark-api-sdk/schemas/Project.json
  carbonmark/.generated/carbonmark-api-sdk/schemas/TokenPrice.json
  carbonmark/.generated/carbonmark-api-sdk/types/DetailedProject.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetProjects.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetProjectsId.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetPurchases.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetUsersWalletorhandle.ts
  carbonmark/.generated/carbonmark-api-sdk/types/Project.ts
  carbonmark/.generated/carbonmark-api-sdk/types/TokenPrice.ts
  carbonmark/.generated/carbonmark-api-sdk/types/index.ts
  carbonmark/.generated/carbonmark-api.schema.json
  carbonmark/components/AssetDetails/index.tsx
  carbonmark/components/ProjectCard/index.tsx
  carbonmark/components/Stats/StatsBar.tsx
  carbonmark/components/Stats/index.tsx
  carbonmark/components/pages/Project/BuyOptions/PoolPrice.tsx
  carbonmark/components/pages/Project/BuyOptions/SellerListing.tsx
  carbonmark/components/pages/Project/ProjectHeader/index.tsx
  carbonmark/components/pages/Project/ProjectTags/index.tsx
  carbonmark/components/pages/Project/Purchase/InactivePurchase.tsx
  carbonmark/components/pages/Project/Purchase/Listing/PurchaseForm.tsx
  carbonmark/components/pages/Project/Purchase/Listing/index.tsx
  carbonmark/components/pages/Project/Purchase/Pool/PurchaseForm.tsx
  carbonmark/components/pages/Project/Purchase/Pool/SuccessScreen.tsx
  carbonmark/components/pages/Project/Purchase/Pool/index.tsx
  carbonmark/components/pages/Project/Purchase/index.tsx
  carbonmark/components/pages/Project/Retire/Pool/RetireForm.tsx
  carbonmark/components/pages/Project/Retire/index.tsx
  carbonmark/components/pages/Project/index.tsx
  carbonmark/components/pages/Retire/index.tsx
  carbonmark/components/pages/Retirements/SingleRetirement/index.tsx
  carbonmark/components/pages/Users/SellerUnconnected/index.tsx
  carbonmark/hooks/useConnectedUser.ts
  carbonmark/hooks/useFetchProjects.ts
  carbonmark/lib/actions.ts
  carbonmark/lib/api/swr.keys.ts
  carbonmark/lib/constants.ts
  carbonmark/lib/listingsGetter.ts
  carbonmark/lib/projectGetter.ts
  carbonmark/lib/types/carbonmark.types.ts
  carbonmark/pages/projects/[project_id]/index.tsx
  carbonmark/pages/projects/[project_id]/purchase/[listing_id].ts
  carbonmark/pages/projects/index.tsx
Labels: QA done

#2081 Emc/chore/2079-kubb-v2
  carbonmark/.generated/carbonmark-api-sdk/clients/getActivities.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/getCategories.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/getCountries.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/getProjects.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/getProjectsId.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/getProjectsIdActivity.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/getPurchasesId.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/getUsersWalletorhandle.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/getVintages.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/postLogin.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/postLoginVerify.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/postUsers.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/putUsersWallet.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/index.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/useGetActivities.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/useGetCategories.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/useGetCountries.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/useGetProjects.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/useGetProjectsId.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/useGetProjectsIdActivity.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/useGetPurchasesId.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/useGetUsersWalletorhandle.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/useGetVintages.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/usePostLogin.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/usePostLoginVerify.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/usePostUsers.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/usePutUsersWallet.ts
  carbonmark/.generated/carbonmark-api-sdk/index.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetActivities.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetCategories.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetCountries.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetProjects.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetProjectsId.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetProjectsIdActivity.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetPurchasesId.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetUsersWalletorhandle.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetVintages.ts
  carbonmark/.generated/carbonmark-api-sdk/types/PostLogin.ts
  carbonmark/.generated/carbonmark-api-sdk/types/PostLoginVerify.ts
  carbonmark/.generated/carbonmark-api-sdk/types/PostUsers.ts
  carbonmark/.generated/carbonmark-api-sdk/types/PutUsersWallet.ts
  carbonmark/.generated/carbonmark-api.schema.json
  carbonmark/hooks/useFetchProjects.ts
  carbonmark/kubb.config.ts
  carbonmark/lib/utils/array.utils.ts
  carbonmark/lib/utils/object.utils.ts
  carbonmark/lib/utils/string.utils.ts
  carbonmark/package.json
  package-lock.json
Labels: QA in progress

#2048 [KLIMADAO/Klimadao] Polygon-digital-carbon for retirement data
  carbonmark/components/pages/Portfolio/Retire/RetireForm/index.tsx
  carbonmark/components/pages/Portfolio/Retire/RetirementSidebar/index.tsx
  carbonmark/components/pages/Portfolio/Retire/index.tsx
  carbonmark/components/pages/Retire/Activity/Quotes.tsx
  carbonmark/components/pages/Retire/Activity/Table.tsx
  carbonmark/components/pages/Retirements/List/Item.tsx
  carbonmark/components/pages/Retirements/SingleRetirement/ProjectDetails/index.tsx
  carbonmark/components/pages/Retirements/SingleRetirement/TransactionDetails/index.tsx
  carbonmark/components/pages/Retirements/SingleRetirement/index.tsx
  carbonmark/lib/actions.ts
  carbonmark/lib/convertCountryCodeToName.ts
  carbonmark/lib/getCategoryFromMethodology.ts
  carbonmark/lib/getProjectTokenFromBridgeProtocol.ts
  carbonmark/lib/getTokenInfo.ts
  carbonmark/lib/offsetGetter.ts
  carbonmark/lib/registryAPIs/ICR/ICR_API.ts
  carbonmark/lib/retireQueries.ts
  carbonmark/lib/retirementCertificates/index.ts
  carbonmark/lib/retirementDataQueries/getProjectInfoViaPolygonDigitalCarbon.ts
  carbonmark/lib/retirementDataQueries/retirementDataViaPolygonDigitalCarbon.ts
  carbonmark/lib/types/carbonmark.types.ts
  carbonmark/lib/waitForIndexStatus.ts
  carbonmark/pages/api/certificates/[beneficiaryAddress]/[retirementIndex]/index.ts
  carbonmark/pages/api/retirements/[beneficiary_address]/index.ts
  carbonmark/pages/portfolio/[project_token_0x]/retire/index.tsx
  carbonmark/pages/retirements/[beneficiary]/[retirement_index].tsx
  carbonmark/pages/retirements/[beneficiary]/index.tsx
  carbonmark/public/icons/ICR.png
  lib/constants/index.ts
  lib/types/subgraph.ts
  lib/utils/index.ts
  lib/utils/subgraph/queryPolygonBridgedCarbon.ts
  site/components/pages/Retirements/List/Item.tsx
  site/components/pages/Retirements/SingleRetirement/DownloadCertificateButton/generateCertificate.ts
  site/components/pages/Retirements/SingleRetirement/ProjectDetails/index.tsx
  site/components/pages/Retirements/SingleRetirement/index.tsx
  site/lib/getTokenInfo.ts
  site/pages/retirements/[beneficiary]/[retirement_index].tsx
  site/pages/retirements/[beneficiary]/index.tsx
Labels: QA done

#2127 Fix Retirement Quantities
  carbonmark/components/pages/Retire/Activity/Overview.tsx
  carbonmark/components/pages/Retirements/List/Item.tsx
  carbonmark/components/pages/Retirements/SingleRetirement/index.tsx
  carbonmark/lib/retirementDataQueries/retirementDataViaPolygonDigitalCarbon.ts
  carbonmark/pages/api/certificates/[beneficiaryAddress]/[retirementIndex]/index.ts
  carbonmark/pages/api/retirements/[beneficiary_address]/index.ts
  carbonmark/pages/retirements/[beneficiary]/index.tsx
Labels: QA done

#2098 Makka / #1993 new feature banner for bank transfer feature
  app/locale/en-pseudo/messages.po
  app/locale/en/messages.po
  carbon/locale/en-pseudo/messages.po
  carbon/locale/en/messages.po
  carbonmark/components/FeatureBanner/index.tsx
  carbonmark/components/FeatureBanner/styles.ts
  carbonmark/components/Layout/index.tsx
  carbonmark/components/Layout/styles.ts
  carbonmark/components/pages/Projects/Banners/BankTransfer.tsx
  carbonmark/components/pages/Projects/index.tsx
  carbonmark/components/pages/Projects/styles.ts
  carbonmark/lib/constants.ts
  carbonmark/locale/en-pseudo/messages.po
  carbonmark/locale/en/messages.po
  site/locale/en-pseudo/messages.po
  site/locale/en/messages.po
Labels: QA done

#2051 [API] ICR API Integration
  carbonmark-api/package.json
  carbonmark-api/src/.generated/mocks/icr.mocks.ts
  carbonmark-api/src/.generated/types/icr.types.ts
  carbonmark-api/src/app.constants.ts
  carbonmark-api/src/graphql/icr.fragments.gql
  carbonmark-api/src/graphql/icr.gql
  carbonmark-api/src/models/Asset.model.ts
  carbonmark-api/src/models/Project.model.ts
  carbonmark-api/src/models/Purchase.model.ts
  carbonmark-api/src/routes/activities/get.ts
  carbonmark-api/src/routes/countries/get.ts
  carbonmark-api/src/routes/projects/[id]/activity/get.ts
  carbonmark-api/src/routes/projects/get.ts
  carbonmark-api/src/routes/projects/get.utils.ts
  carbonmark-api/src/routes/purchases/[id]/get.ts
  carbonmark-api/src/routes/purchases/get.utils.ts
  carbonmark-api/src/routes/users/[walletOrHandle]/get.ts
  carbonmark-api/src/routes/users/[walletOrHandle]/get.utils.ts
  carbonmark-api/src/routes/vintages/get.ts
  carbonmark-api/src/utils/CreditId.ts
  carbonmark-api/src/utils/ICR/icr.utils.ts
  carbonmark-api/src/utils/gqlSdk.ts
  carbonmark-api/src/utils/helpers/activities.utils.ts
  carbonmark-api/src/utils/helpers/getProjectPoolInfo.ts
  carbonmark-api/src/utils/helpers/utils.ts
  carbonmark-api/src/utils/marketplace.utils.ts
  carbonmark-api/test/fixtures/icr.ts
  carbonmark-api/test/plugins/rate-limit.test.ts
  carbonmark-api/test/routes/countries/get.test.ts
  carbonmark-api/test/routes/projects/[id]/get.test.ts
  carbonmark-api/test/routes/projects/get.test.mocks.ts
  carbonmark-api/test/routes/projects/get.test.ts
  carbonmark-api/test/routes/users/get.test.ts
  carbonmark-api/test/routes/vintages/get.test.ts
  carbonmark-api/test/test.constants.ts
Labels: carbonmark-api

#2162 [api] Support both images and externalMedia media from cms projects
  carbonmark-api/package.json
  carbonmark-api/src/.generated/types/cms.types.ts
  carbonmark-api/src/graphql/cms.fragments.gql
  carbonmark-api/src/routes/projects/get.utils.ts
Labels: QA done, carbonmark-api

#2163 [api] Remove ICR artifacts
  carbonmark-api/package.json
  carbonmark-api/src/.generated/types/icr.types.ts
  carbonmark-api/src/graphql/icr.gql
  carbonmark-api/src/models/Project.model.ts
  carbonmark-api/src/models/Purchase.model.ts
Labels: carbonmark-api

#2141 chore: 2090add connected wallet to portofolio page
  carbonmark/components/pages/Portfolio/ConnectedWallet/index.tsx
  carbonmark/components/pages/Portfolio/ConnectedWallet/styles.ts
  carbonmark/components/pages/Portfolio/PortfolioSidebar.tsx
  carbonmark/components/pages/Portfolio/index.tsx
  lib/utils/concatAddress/index.ts
Labels: QA done

#2180 [api] Fix `listings` endpoint for ICR
  carbonmark-api/package.json
  carbonmark-api/src/utils/helpers/listings.utils.ts
Labels: carbonmark-api

#2118 Fix moss single retirement page
  carbonmark/pages/retirements/[beneficiary]/[retirement_index].tsx
  lib/constants/index.ts
Labels: QA done, carbonmark

#2195 Upgrade to api version v6.0.0
  carbonmark/.generated/carbonmark-api-sdk/clients/getRetirements.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/getRetirementsId.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/getRetirementsIdProvenance.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/index.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/operations.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/postLogin.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/postLoginVerify.ts
  carbonmark/.generated/carbonmark-api-sdk/clients/putUsersWallet.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/index.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/useGetRetirements.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/useGetRetirementsId.ts
  carbonmark/.generated/carbonmark-api-sdk/hooks/useGetRetirementsIdProvenance.ts
  carbonmark/.generated/carbonmark-api-sdk/schemas/CarbonCredit.json
  carbonmark/.generated/carbonmark-api-sdk/schemas/Project.json
  carbonmark/.generated/carbonmark-api-sdk/schemas/ProvenanceRecord.json
  carbonmark/.generated/carbonmark-api-sdk/schemas/Purchase.json
  carbonmark/.generated/carbonmark-api-sdk/schemas/Retirement.json
  carbonmark/.generated/carbonmark-api-sdk/schemas/User.json
  carbonmark/.generated/carbonmark-api-sdk/types/CarbonCredit.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetProjects.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetProjectsId.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetPurchases.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetPurchasesId.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetRetirements.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetRetirementsId.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetRetirementsIdProvenance.ts
  carbonmark/.generated/carbonmark-api-sdk/types/GetUsersWalletorhandle.ts
  carbonmark/.generated/carbonmark-api-sdk/types/PostLogin.ts
  carbonmark/.generated/carbonmark-api-sdk/types/PostLoginVerify.ts
  carbonmark/.generated/carbonmark-api-sdk/types/PostUsers.ts
  carbonmark/.generated/carbonmark-api-sdk/types/Project.ts
  carbonmark/.generated/carbonmark-api-sdk/types/ProvenanceRecord.ts
  carbonmark/.generated/carbonmark-api-sdk/types/Purchase.ts
  carbonmark/.generated/carbonmark-api-sdk/types/PutUsersWallet.ts
  carbonmark/.generated/carbonmark-api-sdk/types/Retirement.ts
  carbonmark/.generated/carbonmark-api-sdk/types/User.ts
  carbonmark/.generated/carbonmark-api-sdk/types/index.ts
  carbonmark/.generated/carbonmark-api.schema.json
  carbonmark/components/pages/Users/SellerConnected/Forms/EditProfile.tsx
  carbonmark/components/pages/Users/SellerConnected/index.tsx
  carbonmark/lib/api.ts
  carbonmark/lib/constants.ts
  carbonmark/lib/createUrls.ts
Labels: HIGH PRIORITY, carbonmark

#2193 fix #1404
  carbonmark/components/pages/Retire/FromPortfolio/index.tsx
  carbonmark/components/pages/Retire/FromPortfolio/styles.ts
Labels: carbonmark
